import { toast } from "@superset/ui/sonner";
import { useNavigate } from "@tanstack/react-router";
import { useCallback } from "react";
import { useCheckoutDashboardWorkspace } from "renderer/routes/_authenticated/components/DashboardNewWorkspaceModal/hooks/useCheckoutDashboardWorkspace";
import { useCreateDashboardWorkspace } from "renderer/routes/_authenticated/components/DashboardNewWorkspaceModal/hooks/useCreateDashboardWorkspace";
import { useDashboardNewWorkspaceDraft } from "../../../../../DashboardNewWorkspaceDraftContext";
import { mapLinkedContext } from "./mapLinkedContext";
import { resolveNames } from "./resolveNames";

export interface SubmitAttachment {
	url: string;
	mediaType: string;
	filename?: string;
}

export function useSubmitWorkspace(
	projectId: string | null,
	selectedAgent: string | null,
) {
	const navigate = useNavigate();
	const { closeAndResetDraft, draft } = useDashboardNewWorkspaceDraft();
	const createWorkspace = useCreateDashboardWorkspace();
	const checkoutWorkspace = useCheckoutDashboardWorkspace();

	return useCallback(
		async (files: SubmitAttachment[] = []) => {
			if (!projectId) {
				toast.error("Select a project first");
				return;
			}

			const { branchName, workspaceName, workspaceNameWasAutoGenerated } =
				resolveNames(draft);
			const linkedContext = mapLinkedContext(draft);
			const pendingId = crypto.randomUUID();

			try {
				const result =
					draft.linkedPR !== null
						? await checkoutWorkspace({
								pendingId,
								projectId,
								hostTarget: draft.hostTarget,
								branchName: `pr-${draft.linkedPR.prNumber}`,
								prCheckout: { prNumber: draft.linkedPR.prNumber },
								names: {
									workspaceName: draft.linkedPR.title,
									branchName: `pr-${draft.linkedPR.prNumber}`,
								},
								composer: {
									prompt: draft.prompt,
									runSetupScript: draft.runSetupScript,
								},
								agentId: selectedAgent,
								linkedContext: { ...linkedContext, attachments: files },
							})
						: await createWorkspace({
								pendingId,
								projectId,
								hostTarget: draft.hostTarget,
								names: {
									workspaceName,
									branchName,
									workspaceNameWasAutoGenerated,
								},
								composer: {
									prompt: draft.prompt,
									baseBranch: draft.baseBranch ?? undefined,
									baseBranchSource: draft.baseBranchSource ?? undefined,
									runSetupScript: draft.runSetupScript,
								},
								agentId: selectedAgent,
								linkedContext: { ...linkedContext, attachments: files },
							});

				const workspaceId = result.workspace?.id;
				if (!workspaceId) {
					toast.error("Workspace creation returned no id");
					return;
				}
				const launchTerminalId =
					result.terminals?.find((t) => t.role === "agent")?.id ?? null;

				closeAndResetDraft();
				void navigate({
					to: "/v2-workspace/$workspaceId",
					params: { workspaceId },
					state: { launchTerminalId } as never,
				});
			} catch (err) {
				toast.error(
					err instanceof Error ? err.message : "Failed to create workspace",
				);
			}
		},
		[
			checkoutWorkspace,
			closeAndResetDraft,
			createWorkspace,
			draft,
			navigate,
			projectId,
			selectedAgent,
		],
	);
}
